api/urls.py
from django.urls import path
from django.conf import settings

from . import views

app_name = "api"

urlpatterns = [
    path(
        "spots/",
        views.ParkingSpaceNearCenterAPIView.as_view(),
        name="spots-near-center",
    ),
    path(
        "spot/occupancy/",
        views.ParkingSpaceChangeOccupancyAPIView.as_view(),
        name="change-occupancy",
    ),
    path(
        "spot/posts/<str:spotId>/",
        views.ParkingSpacePostsAPIView.as_view(),
        name="get-spot-posts",
    ),
    path(
        "spot/posts/add-comment/<int:postId>/",
        views.ParkingSpaceAddCommentAPIView.as_view(),
        name="add-comment",
    ),
    path(
        "spot/watches-on-spots/",
        views.WatchOnParkingSpaceAPIView.as_view(),
        name="watches-on-spots",
    ),
    path(
        "spot/add-watch-on-spot/",
        views.AddWatchOnParkingSpaceAPIView.as_view(),
        name="add-watch-on-spot",
    ),
    path(
        "spot/remove-watch-on-spot/",
        views.RemoveWatchOnParkingSpaceAPIView.as_view(),
        name="remove-watch-on-spot",
    ),
]

map/urls.py
from django.urls import path
from django.conf import settings

from . import views

app_name = "map"

urlpatterns = [
    path("parking/", views.MapView.as_view(), name="parking"),
    path(
        "post/<str:parking_spot_id>/",
        views.PostView.as_view(),
        name="post",
    ),
    path(
        "parking/add-spot/",
        views.ParkingSpaceView.as_view(),
        name="add-parking-space",
    ),
    path(
        "spot-redirect/<str:parking_spot_id>/",
        views.ProfileSpotRedirectView.as_view(),
        name="spot-redirect",
    ),
    path(
        "peak-time/<str:parking_spot_id>/",
        views.PeakTimeView.as_view(),
        name="peak-time",
    ),
]

parkrowd/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("map/", include("map.urls")),
    path("api/", include("api.urls")),
    path("", RedirectView.as_view(pattern_name="map:parking", permanent=False)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("logout/", views.UserLogoutView.as_view(), name="logout"),
    path("welcome/", views.UserWelcomeView.as_view(), name="welcome"),
    path("register/", views.UserRegisterView.as_view(), name="register"),
    path("profile/<str:username>/", views.UserProfileView.as_view(), name="profile"),
    path(
        "profile-edit/",
        views.UserProfileEditView.as_view(),
        name="profile-edit",
    ),
    path(
        "profile-delete/",
        views.UserProfileDeleteView.as_view(),
        name="profile-delete",
    ),
    path(
        "password-reset/",
        views.UserPasswordResetView.as_view(),
        name="password-reset",
    ),
    path(
        "password-reset-email-sent/",
        views.UserPasswordResetEmailSentView.as_view(),
        name="password-reset-email-sent",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        views.UserPasswordResetConfirmView.as_view(),
        name="password-reset-confirm",
    ),
    path(
        "password-reset-success/",
        views.UserPasswordResetSuccessView.as_view(),
        name="password-reset-success",
    ),
    path(
        "verification/",
        views.UserVerificationView.as_view(),
        name="verification",
    ),
    path(
        "edit_post/<int:post_id>/",
        views.EditPost.as_view(),
        name="edit-post",
    ),
    path(
        "verification-cancel/<int:id>/",
        views.VerificationCancelView.as_view(),
        name="verification-cancel",
    ),
]

users/models.py
"""customized user model
"""
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin

from map.models import ParkingSpace
from .managers import UserManager


# * Create your models here.
class User(AbstractBaseUser, PermissionsMixin):
    """customized user class"""

    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username = models.CharField(max_length=30, unique=True)
    date_joined = models.DateTimeField(verbose_name="Date Joined", default=timezone.now)
    # * Save an avatar image for a user in path avatars/<username>_avatar
    avatar = models.ImageField(
        upload_to="avatars/",
        height_field=None,
        width_field=None,
        max_length=101,
        default="avatars/ParKrowdDefaultAvatar.jpg",
    )

    description = models.TextField(blank=True)

    # * is_superuser : User can create, edit, and delete ANY object (models)
    is_superuser = models.BooleanField(default=False)
    # * is_staff : User can login to site
    is_staff = models.BooleanField(default=False)
    # * is_admin : User is treated as non-superuser staff member.
    # * Admins can be customized to have certain permissions.
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    # * is_verified: To indicate whether the user has been verified by Admin
    is_verified = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["email"]

    def __str__(self):
        return f"Email: {self.email}\n" f"Username: {self.username}\n"

    @staticmethod
    def has_perm(perm, obj=None, **kwargs):
        """TODO: why overriding the original implementation here"""
        return True

    @staticmethod
    def has_module_perms(app_label, **kwargs):
        """TODO: why overriding the original implementation here"""
        return True


class Post(models.Model):
    title = models.CharField(max_length=200)
    post = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(verbose_name="Date created", default=timezone.now)
    parking_space = models.ForeignKey(ParkingSpace, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Comment(models.Model):
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    created_at = models.DateTimeField(verbose_name="Date created", default=timezone.now)

    def __str__(self):
        return (
            f"Comment created by {self.author.username} under Post '{self.post.title}'"
        )


class UserVerification(models.Model):
    status_list = [
        ("submitted", "Submitted"),
        ("in_progress", "In progress"),
        ("cancelled", "Cancelled"),
        ("verified", "Verified"),
    ]
    username = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="verification"
    )
    business_name = models.CharField(max_length=200)
    business_type = models.CharField(max_length=200)
    business_address = models.CharField(max_length=200)
    uploaded_file = models.FileField(upload_to="verification_files/")
    submitted_at = models.DateTimeField(default=timezone.now, editable=False)
    updated_at = models.DateTimeField(default=timezone.now, editable=False)
    status = models.CharField(max_length=200, choices=status_list, default="submitted")

    def save(self, *args, **kwargs):
        # Update the updated_at whenever the object is saved / modified
        self.updated_at = timezone.now()
        super(UserVerification, self).save(*args, **kwargs)

    class Meta:
        # Set the default ordering to be the descending order of submission time
        ordering = ["-submitted_at"]


class UserWatchedParkingSpace(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    parking_space = models.ForeignKey(
        ParkingSpace,
        on_delete=models.CASCADE,
    )
    threshold = models.IntegerField(default=80)

users/forms.py
"""user forms

Creating Model Forms
https://docs.djangoproject.com/en/4.2/topics/forms/modelforms/

Difference between Model and Forms
https://stackoverflow.com/questions/5481713/whats-the-difference-between-django-models-and-forms
"""

from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import (
    SetPasswordForm,
    UserCreationForm,
    PasswordResetForm,
    AuthenticationForm,
)

from .models import User, Post, UserVerification

from django.core.validators import FileExtensionValidator


class UserLoginForm(AuthenticationForm):
    """login form"""

    username = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Enter username or email"}
        )
    )

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Enter password"}
        )
    )

    remember_me = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={"class": "form-check-input", "type": "checkbox"}
        ),
    )

    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise forms.ValidationError("This account is inactive.", code="inactive")

    class Meta:
        """_summary_"""

        model = User
        fields = ["username", "password"]


class UserRegisterForm(UserCreationForm):
    """user registration form"""

    username = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Enter username"}
        )
    )

    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Enter email"}
        )
    )

    """
    avatar = forms.ImageField(
        widget = forms.ClearableFileInput(
            attrs={"class": "form-control"}
        )
    )
    """

    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Enter Password"}
        )
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Confirm Password"}
        )
    )

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


"""
Now in map.forms.py

 class PostForm(forms.ModelForm):
     class Meta:
        model = Post
        fields = ["title", "post", "created_at"]
"""


class UserVerificationForm(forms.ModelForm):
    BUSINESS_TYPES = (
        ("Public Parking Lot Owner", "Public Parking Lot Owner"),
        ("Private Parking Lot Owner", "Private Parking Lot Owner"),
        ("Street Business Owner", "Street Business Owner"),
    )
    business_name = forms.CharField(max_length=200)
    business_type = forms.ChoiceField(choices=BUSINESS_TYPES)
    business_address = forms.CharField(max_length=200)
    uploaded_file = forms.FileField(
        label="Choose a file",
        required=True,
        validators=[
            FileExtensionValidator(
                allowed_extensions=["pdf", "doc", "docx", "png", "jpg", "jpeg"]
            )
        ],
    )

    class Meta:
        model = UserVerification
        fields = ["business_name", "business_type", "business_address", "uploaded_file"]

    def clean_uploaded_file(self):
        uploaded_file = self.cleaned_data["uploaded_file"]
        if not uploaded_file:
            raise forms.ValidationError("You must upload a file.")
        return uploaded_file


class UserPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                "type": "email",
                "class": "form-control",
                "placeholder": "name@example.com",
            }
        )
    )

    email_template_name = "users/password_reset_email.html"
    subject_template_name = "users/password_reset_email_subject.txt"

    class Meta:
        fields = ["email"]


class UserPasswordResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(
        strip=False,
        label="New password",
        help_text=password_validation.password_validators_help_text_html(),
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Enter Password"}
        ),
    )
    new_password2 = forms.CharField(
        strip=False,
        label="New password confirmation",
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Confirm Password"}
        ),
    )

    class Meta:
        fields = ["new_password1", "new_password2"]


class EditPostForm(forms.ModelForm):
    """edit post form"""

    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Post title goes here",
            }
        )
    )

    post = forms.CharField(
        widget=forms.Textarea(
            attrs={"class": "form-control", "placeholder": "Post content goes here"}
        )
    )

    class Meta:
        model = Post
        fields = ["title", "post"]

parkrowd/users/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .backends import EmailOrUsernameAuthenticationBackend as EoU

from django.contrib import messages
from django.contrib import auth
from django.contrib.auth.forms import AuthenticationForm

from django.views import View
from .forms import UserRegisterForm, UserLoginForm

from .models import User

SESSION_COOKIE_EXPIRATION = 86400


# Create your views here.

class UserRegisterView(View):
    form_class              = UserRegisterForm
    template_name           = 'register.html'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.email = request.POST.get('email')
            user.set_password(request.POST.get('password1'))
            user.save()
            #messages.success(request, 'Success')
            return redirect("/welcome")
        else:
            return render(request, self.template_name, {'form': form})



class UserLoginView(View):
    form_class                      = UserLoginForm
    template_name                   = 'login.html'

    def get(self, request):
        form                        = self.form_class
        return render( request, self.template_name, { 'form': form } )

    def post(self, request):
        form                        = self.form_class(request.POST)    

        username                    = request.POST.get('username')
        password                    = request.POST.get('password')
        remember_me                 = request.POST.get('remember_me')

        user                        = EoU.authenticate(request, username=username, password=password)
        if not user:
            messages.error( request, 'No such user exists with those credentials exist' )
        else:
            auth.login(request, user)
            messages.success( request, 'You have successfully logged in!' )

            if remember_me: request.session.set_expiry(SESSION_COOKIE_EXPIRATION)
            else: request.session.set_expiry(0)

            return redirect('/profile/' + user.username)
        
        return render( request, self.template_name, { 'form': form } )



class UserLogoutView(View):
    template_name           = 'logout.html'
    
    def get(self, request):
        return redirect('/login')

    def post(self, request):
        auth.logout(request)
        return redirect('/login')
    
class UserWelcomeView(View):
    template_name           = 'welcome.html'
    
    def get(self, request):
        return render(request, self.template_name )



class UserProfileView(View):
    model                   = User
    template_name           = 'profile.html'

    def get(self, request, username):
        user                = get_object_or_404(User, username=username)
        return render( request, self.template_name, {'user': user})

    def post(self, request, username):
        user                = get_object_or_404(User, username=username)
        return render( request, self.template_name )
    

users/templates/users/edit_post.html
<!-- @format -->
{% extends "parkrowd/main.html" %} {% block content %}
<div class="container">
    <div class="row justify-content-center py-4">
      <div class="col-md-9">
        <h3 class="text-center">Edit Post</h3>
        <form method="post">
          {% csrf_token %}
          <div class="form-group">
            <label for="title">Title:</label>
            <input type="text" id="title" name="title" class="form-control" value="{{ post.title }}">
        </div>
        <div class="form-group">
            <label for="post">Post:</label>
            <textarea id="post" name="post" class="form-control" rows="5">{{ post.post }}</textarea>
        </div>
          <div class="row py-4 justify-content-center">
            <div class="col-md-2">
              <button type="submit" class="btn btn-primary">Save</button>
            </div>
            <div class="col-md-1">
                <a href="{% url 'users:profile' user.username %}" class="btn btn-secondary">Cancel</a>
            </div>
          </div>
        </form>
        <div style="color: red">{{ form.errors }}</div>
      </div>
    </div>
  </div>
  </div>
{% endblock %}

users/templates/users/login.html
{% extends "parkrowd/main.html" %}

{% block content %}
<div class="container">
    <div class="row justify-content-center py-4">
        <div class="col-md-9">
            <h3 class="text-center">Login</h3>
            <form method="post">
                {% csrf_token %}
                <div class="form-group py-1">
                    <label for="id_username">Username or email address</label>
                    {{ form.username }}
                </div>
                <div class="form-group py-1">
                    <label for="id_password">Password</label>
                    {{ form.password }}
                </div>
                <div class="form-check py-1">
                    <label class="form-check-label" for="id_remember_me">Remember Me</label>
                    {{ form.remember_me }}
                </div>
                <div class="row py-3 justify-content-center text-center">
                    <div class="col-md-2">
                        <button type="submit" class="btn btn-primary">Sign In</button>
                    </div>
                </div>
                <div class="row text-center">
                    <div class="col-12">
                        Consider joining? Register <a href="{% url 'users:register' %}">here</a>.
                    </div>
                </div>
                <div class="row text-center">
                    <div class="col-12">
                        Forget your password? Reset <a href="{% url 'users:password-reset' %}">here</a>.
                    </div>
                </div>
            </form>
            {% if messages %}
            <ul class="messages" style="color: red">
                {% for message in messages %}
                {% if message.tags == 'error' %}
                <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                    {% endif %}
                    {% endfor %}
            </ul>
            {% endif %}
            {{ form.errors.non_field_errors }}
            <ul class="list-unstyled">
                {% for field, error_list in form.errors.items %}
                {% for error in error_list %}
                <li class="text-danger">{{ error }}</li>
                {% endfor %}
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset.html
{% extends "parkrowd/main.html" %}
{% load static %}
{% block header %}
<link href="{% static 'users/password_reset.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}


<main class="form-password-reset text-center justify-content-center">
  <h1 class="h3 mb-1">Forgot password?</h1>
  <h1 class="h3 mb-3">We got you</h1>
  <div class="mb-3">Enter the email you used to register with us</div>
  <form method="POST">
    {% csrf_token %}
    <div class="form-floating">
      {{ form.email }}
      <label for="email">Email address</label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Send Email</button>
  </form>
  <div class="row text-center pt-4">
    <div class="col-12">
      Login <a href="{% url 'users:login' %}">here</a>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col"> {% if messages %}
      {% for message in messages %}
      <div class="alert alert-warning pb-1" role="alert">
        <p>{{message | safe }}</p>
      </div>
      {% endfor %}
      {% endif %}
    </div>
  </div>
  <div class="row mt-4">
    <div class="col">
      {% for field, error_list in form.errors.items %}
      {% for error in error_list %}
      <div class="alert alert-warning pb-1" role="alert">
        <p>{{error | safe }}</p>
      </div>
      {% endfor %}
      {% endfor %}
    </div>
  </div>
</main>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends "parkrowd/main.html" %}

{% load static %}
{% block header %}
<link href="{% static 'users/password_reset_confirm.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
<main class="form-password-reset-confirm text-center">
  <h1 class="h3 mb-4">Reset Password</h1>
  <form method="POST">
    {% csrf_token %}
    <div class="form-floating">
      {{ form.new_password1 }}
      <label for="email">Enter new password</label>
    </div>
    <div class="form-floating">
      {{ form.new_password2 }}
      <label for="email">Confirm new password</label>
    </div>
    <button class="w-100 btn btn-lg btn-primary mt-4" type="submit">Reset Password</button>
  </form>
  <div class="row text-center pt-4">
    <div class="col-12">
      Login <a href="{% url 'users:login' %}">here</a>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col"> {% if messages %}
      {% for message in messages %}
      <div class="alert alert-warning pb-1" role="alert">
        <p>{{message | safe }}</p>
      </div>
      {% endfor %}
      {% endif %}
    </div>
  </div>
  <div class="row mt-4">
    <div class="col">
      {% for field, error_list in form.errors.items %}
      {% for error in error_list %}
      <div class="alert alert-warning pb-1" role="alert">
        <p>{{error | safe }}</p>
      </div>
      {% endfor %}
      {% endfor %}
    </div>
  </div>
  {% endblock %}
</main>

users/templates/users/password_reset_email.html
{% autoescape off %}
Hello {{ user.username }},

We received a request to reset the password for your account for this email address. To initiate the password reset
process for your account, click the link below.

{{ protocol }}://{{ domain }}{% url 'users:password-reset-confirm' uidb64=uid token=token %}

This link can only be used once. If you need to reset your password again, please visit
{{ protocol }}://{{domain}}/{% url 'users:password-reset' %} and request another reset.

If you did not make this request, you can simply ignore this email.

Sincerely,
Parkrowd Team

{% endautoescape %}

users/templates/users/profile.html
<!-- @format -->

{% extends "parkrowd/main.html" %} {% block navbarEnd %} {% if request.user.is_authenticated %}
<a
  href="#"
  class="btn btn-outline-warning"
  onClick="document.getElementById('logout-form').submit()"
>
  Logout</a
>

<form id="logout-form" method="POST" action="{% url 'users:logout' %}">
  {% csrf_token %}
  <input type="hidden" />
</form>
{% endif %} {% endblock %} {% block content %}
<div class="container-lg">
  <div class="card">
    <div class="card-header">{{ user.username_human }}'s Profile</div>
    <div class="card-body">
      <div class="card-text d-flex align-items-center">
        <div class="d-flex align-items-center card-body">
          <!--Profile Avatar-->
          <div class="image">
            <img
              src="{{ user.avatar.url }}"
              width="100"
              height="100"
              style="vertical-align: top; margin: 20px 20px; float: left; border: 5px solid black"
            />
          </div>
          <!--END Profile Avatar-->

          <!-- User Info -->
          <div class="ml-3 w-100">
            <h4 class="mb-0 mt-0">{{ user.username_human }}</h4>
            <span><i>{{ user.description }}</i></span>
            <div class="p-2 mt-2 d-flex justify-content-between rounded">
              <div class="col-md-10">
                <div class="row">
                  <div class="col-md-auto">Email:</div>
                  <div class="col">{{ user.email }}</div>
                </div>
                {% if user.is_verified %}
                <div class="row">
                  <div class="col-md-auto">
                    Business Type
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="16"
                      height="16"
                      fill="currentColor"
                      class="bi bi-check-circle-fill"
                      viewBox="0 0 16 16"
                    >
                      <path
                        d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"
                      />
                    </svg>
                    :
                  </div>
                  <div class="col">{{ user_verification.business_type }}</div>
                </div>
                {% endif %}
              </div>
            </div>
          </div>
          <!-- END User Info -->
        </div>
      </div>
    </div>
    <div class="card-footer pb-3">
      <!--Delete Account-->
      {% if request.user.is_authenticated and is_user_owner_of_profile %}
      <div class="button mt-2 d-flex flex-row align-items-center justify-content-end">
        <!--Edit Profile-->
        <a href="{% url 'users:profile-edit' %}" class="btn btn-primary mx-1">Edit</a>
        <!--END Edit Profile-->
        <a href="{% url 'users:verification' %}" class="btn btn-outline-primary mx-2">Verify</a>
        <button
          type="button"
          class="btn btn-danger mx-2"
          data-bs-toggle="modal"
          data-bs-target="#deleteAccountModal"
        >
          Delete Account
        </button>
      </div>
      <!-- Delete Account Modal -->
      <div
        class="modal fade"
        id="deleteAccountModal"
        tabindex="-1"
        role="dialog"
        aria-labelledby="deleteAccount"
        aria-hidden="true"
      >
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteAccountTitle">Delete Account</h5>
              <button
                type="button"
                class="btn-close"
                data-bs-dismiss="modal"
                aria-label="Close"
              ></button>
            </div>
            <div class="modal-body">Are you sure you want to delete your account?</div>
            <div class="modal-footer">
              <form action="{% url 'users:profile-delete' %}" method="POST">
                {% csrf_token %}
                <button type="submit" name="delete_profile" class="btn btn-danger">Yes</button>
              </form>
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                Cancel
              </button>
            </div>
          </div>
        </div>
      </div>
      {% if messages %}
      <ul class="messages">
        {% for message in messages %} {% if message.tags == 'error' %}
        <li>{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endif %} {% endfor %}
      </ul>
      {% endif %} {% endif %}
      <!--END Delete Account-->
    </div>
  </div>

  <hr class="mt-4" />
  <!--Spots-->
  <div class="row mt-4">
    <h2>User's Spots</h2>
  </div>
  <div class="row">
    {% for spot in user_spots %}
    <div class="col-md-4">
      <div class="spot-box border rounded p-2 m-2">
        <h3>{{ spot.parking_spot_name }}</h3>
        <a href="{% url 'map:spot-redirect' parking_spot_id=spot.parking_spot_id %}" class="btn btn-primary">View Spot</a>
      </div>
    </div>
    {% empty %}
    <div class="col-md-12">
      <p>This user has no spots.</p>
    </div>
    {% endfor %}
  </div>
    <!--END Spots-->
    <!--Posts-->
    <div class="row mt-4">
      <h2>User's Posts</h2>
    </div>
    <div class="row">
      <div class="d-flex flex-wrap">
        {% for post in user_posts %}
        <div class="post-box border rounded p-3 m-2">
          <h3>{{ post.title }}</h3>
          <p>{{ post.post }}</p>
          <p>Posted on {{ post.created_at }}</p>
          {% if request.user == post.author %}
          <a href="{% url 'users:edit-post' post_id=post.id %}" class="btn btn-primary mx-1">Edit</a>
          {% endif %}
        </div>
        {% empty %}
        <p>No posts found for this user.</p>
        {% endfor %}
      </div>
    </div>
    <!--END Posts-->
  </div>
  {% endblock %}
</div>

users/templates/users/profile_edit.html
{% extends "parkrowd/main.html" %}

{% block content %}
{% if request.user.is_authenticated %}
<div class="d-flex justify-content-end py-2 px-2">
    <a href="#" class="btn btn-outline-secondary" onClick="document.getElementById('logout-form').submit()">
        Logout
    </a>
    <form id="logout-form" method="POST" action="{% url 'users:logout' %}">
        {% csrf_token %}
        <input type="hidden" />
    </form>
</div>
{% endif %}
<div class="container-lg">
    <div class="row">
        <h2>Profile Info</h2>
    </div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Username</label>

            {% if exists %}
            <input type="text" class="form-control" name="input-username" value="{{ new_username }}">
            <div style="color: red;">Username already exists</div>
            {% else %}
            <input type="text" class="form-control" name="input-username" value="{{ user.username }}">
            {% endif %}
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" name="input-email" value="{{ user.email }}">
        </div>
        <div class="form-group">
            <label for="avatar">Avatar</label>
            <input type="file" class="form-control" name="input-avatar" value="{{ user.avatar }}">
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <input type="text" class="form-control" name="input-description" value="{{ user.description }}">
        </div>
        <div class="row justify-content-end py-4">
            <div class="col-md-1">
                <button type="submit" class="btn btn-primary mx-4">Save</button>
            </div>
            <div class="col-md-1">
                <a href="{% url 'users:profile' user.username %}" class="btn btn-secondary">Cancel</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}